cluster:
  initial_master_nodes: ""
discovery:
  type: single-node
esJavaOpts: -Xms256m -Xmx256m
replicas: 1
resources:
  limits:
    memory: 1Gi
  requests:
    memory: 512Mi

metrics:
  enabled: false

master:
  autoscaling:
    enabled: false

ingest:
  enabled: false
