apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: monitoring-kube-prometheus-prometheus
  ports:
    - name: web
      port: 9090
      targetPort: 9090
