apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: monitoring-kube-prometheus-prometheus
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      nodePort: 30900  # Any port between 30000–32767
