apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  namespace: sre-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
      - name: visits-service
        image: my-visits-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: sre-lab
spec:
  selector:
    app: visits-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
