apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
  namespace: sre-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - name: my-webapp
        image: my-webapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-webapp
  namespace: sre-lab
spec:
  selector:
    app: my-webapp
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
